Lab2
AndreyVanyuck/Timer pull request #1
Opened 2020-12-16 16:21 UTC by AndreyVanyuck

2020-12-18 13:17 UTC, gmltA requested changes

2020-12-18 13:17 UTC, gmltA commented on app/src/main/java/com/example/timerppo/Activity/CreateWorkoutActivity.java
> +                    db.timerDao().insert(workoutModel);
All this code goes to ViewModel. You shouldn't interact with DB from your view layer.

2020-12-18 13:17 UTC, gmltA commented on app/src/main/java/com/example/timerppo/Activity/MainActivity.java
> +        CustomAdapter adapter = new CustomAdapter(this, R.layout.list_item, db.timerDao().getAll(), db);
Adaptor must not access DB.

2020-12-27 16:30 UTC, gmltA requested changes
If only I could compile this project... Gonna ask you about APK I can run.

2020-12-27 18:53 UTC, AndreyVanyuck commented
Added apk and screenshots

2020-12-28 17:11 UTC, closed without merging